name: Update Sing-box Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # 每4小时运行一次
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set DNS to Alidns
        run: |
          # 强制将 Actions 容器的 DNS 改为阿里 DNS 提高解析速度
          sudo echo "nameserver 223.5.5.5" | sudo tee /etc/resolv.conf
          sudo echo "nameserver 223.6.6.6" | sudo tee -a /etc/resolv.conf

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config.json
          git diff --staged --quiet || (git commit -m "auto: update nodes" && git push)
